[server]
port = 8000
static = true

[log]
level = "trace"

[auth]
issuer = "https://fuzzywuzzie.auth0.com/"
secret = "6kFKU7K7sRcQgzvsyZYc16kHJL2mmJ4uzsXHlbzaEwPS6rxYWT5bJ5J0MmBr0HCq"

[tmdb]
key = "f0ac48748ed6a83078785074bc749471"